; ===Default Variables===

[Variables]
; --User Changeable--
; Container Background Color (Dark)
BackgroundDarkColor=60,60,60,212
; Container Border Color (Dark)
BorderDarkColor=36,36,36,212
; Accent color used for things like system monitoring meters
HighlightColor=20,160,220,212
; Accent color used when a measure's reading is worth alerting
AlertColor=240,20,220,212

; CPU Meter
CPURefresh= 1

; Drive Meter
DriveRefresh= 6

; --Hard Coded--
DisplayH=#WORKAREAHEIGHT#
DisplayHhalf=(#WORKAREAHEIGHT# / 2)
DisplayW=#WORKAREAWIDTH#
DisplayWhalf=(#WORKAREAWIDTH# / 2)

; ===Measures===
